# Foundry Configuration for ZEPHIS Protocol

[profile.default]
# Source and library directories
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Compiler settings
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 2
fuzz = { runs = 1000, max_test_rejects = 65536 }
invariant = { runs = 100, depth = 50, fail_on_revert = true }

# Gas settings
gas_limit = 30_000_000
gas_price = 20_000_000_000

# Coverage settings
coverage = true

# Format settings
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"

# Remappings for imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/ds-test/src/"
]

# Security-focused profile
[profile.security]
src = "src"
out = "out/security"
test = "test"
optimizer = false  # Disable optimizer for security testing
verbosity = 3
fuzz = { runs = 50000, max_test_rejects = 100000 }
invariant = { runs = 500, depth = 100 }

# Gas optimization profile
[profile.gas]
src = "src"
out = "out/gas"
test = "test"
optimizer = true
optimizer_runs = 10000
via_ir = true
verbosity = 1

# CI profile for continuous integration
[profile.ci]
src = "src"
out = "out/ci"
test = "test"
optimizer = true
optimizer_runs = 200
verbosity = 1
fuzz = { runs = 1000 }
invariant = { runs = 50, depth = 25 }